### ISSUE TITLE
Is there event add/edit functionality with database support ?

### ISSUE THREAD

**Issue by prakashmalviya** [SUKOHI/Julius#2]
Hi,

I have checked many of the calendar packages on laravel but none of them have event add/edit functionality dynamically with database support.

Is there your package support for the same ?

Thanks,

**Comment by SUKOHI** [comment]
Hi, prakashmalviya.
Thank you for your message.

Unfortunately, this package doesn't have the functionality you want.
Sorry.

**Comment by prakashmalviya** [comment]
ok np!
